name: Run Story Generator

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
    
jobs:
  generate-story:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-generativeai requests Pillow soundfile numpy
        pip install ipython google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2
        
    - name: Set up Gemini API Key
      run: |
        # Using one of the provided API keys
        echo "GEMINI_API_KEY=AIzaSyAqbqE86FKFXS6t5qrpXJVj9jAf-arQ1Js" >> $GITHUB_ENV
        echo "GEMINI_API_KEY is set"
        
    - name: Run Story Generator
      run: |
        python story_generator_standalone.py
        
    - name: Archive story outputs
      uses: actions/upload-artifact@v4
      with:
        name: story-output
        path: |
          temp_dir/**/*.mp4
          temp_dir/**/*.jpg
          temp_dir/**/*.wav
          temp_dir/**/*.txt
